import "./globals.css";
import { Roboto } from "next/font/google";
import { Header } from "@/widgets/Header";
import { Footer } from "@/widgets/Footer";
import { StoreProvider } from "@/shared/store/StoreProvider";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={roboto.className}
				style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}
			>
				<StoreProvider>
					<div id="modalRoot"></div>
					<div id="dropRoot"></div>
					<Header />
					<main style={{ flex: "1 1 auto", padding: "24px 0" }}>
						{children}
					</main>
					<Footer />
				</StoreProvider>
			</body>
		</html>
	);
}
